apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: megatest48-poi-map-app-dev
  annotations:
    argocd/app-name: megatest48-poi-map-app-dev
    backstage.io/kubernetes-id: megatest48-poi-map-app
    backstage.io/kubernetes-namespace: megatest48
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/megatest48-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/megatest48/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/megatest48/deployments/megatest48-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/megatest48-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://megatest48-poi-map-app-megatest48.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/megatest48"
  system: workshop-system-megatest48
  consumesApis:
    - gateway-api-megatest48
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-megatest48
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/megatest48"
